name: echomind_app
description: EchoMind AI Error Tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.0
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
